# Generated by Django 5.0.1 on 2024-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdb',
            name='file_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
