# Generated by Django 5.0.1 on 2024-01-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0002_apkdb_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkdb',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
