# Generated by Django 5.0.1 on 2024-01-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0003_alter_apkdb_file_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apkDB',
            new_name='Apk',
        ),
    ]
