# Generated by Django 5.0.1 on 2024-01-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0004_rename_apkdb_apk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('class_rf', models.IntegerField()),
                ('class_dt', models.IntegerField()),
                ('class_lr', models.IntegerField()),
            ],
        ),
    ]
