# Generated by Django 5.0.1 on 2024-03-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appform', '0005_analysishistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('malicious_count', models.IntegerField(default=0)),
                ('genuine_count', models.IntegerField(default=0)),
            ],
        ),
    ]
